export const GET_FRIENDS_ATTEMPT = 'GET_FRIENDS_ATTEMPT';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const GET_FRIENDS_FAIL = 'GET_FRIENDS_FAIL';
export const GET_FRIENDS_SUGGESTIONS_ATTEMPT = 'GET_FRIENDS_SUGGESTIONS_ATTEMPT';
export const GET_FRIENDS_SUGGESTIONS_SUCCESS = 'GET_FRIENDS_SUGGESTIONS_SUCCESS';
export const GET_FRIENDS_SUGGESTIONS_FAIL = 'GET_FRIENDS_SUGGESTIONS_FAIL';
export const RESET_FRIENDS = 'RESET_FRIENDS';
